### PR TITLE
Add fallback metadata for missing image sizes

### LINKED ISSUE #31: Requesting a missing image size can result in a broken / missing file
In WP core there are instances where an implicit image size such as `post-thumbnail` is requested or referenced such as when setting a featured image. If the AMF provider has not generated appropriate sizes metadata for the current site, and the provider does not support dynamic image sizing then AMF should fall back to the original.

### PR DESCRIPTION
**Pull request by roborourke**
Rather than returning a broken link if an image size is requested that was not given by the provider.

Returns early in the case of dynamic image resizing support, can handle in a separate filter and PR.

Fixes #31

Before:
Screenshot 2021-06-09 at 17 33 23

After:
Screenshot 2021-06-09 at 17 32 27

Note the "medium_large" size.

### CODE REVIEW

**Review by jazzsequence — CHANGES_REQUESTED** [review]
This seems to work on the backend but something is changing the filename on the frontend to repeat the path to the file as a prefix for the file, e.g.:

`https://altis-dev.altis.dev/tachyon/sites/84/2021/06/https://altis-dev.altis.dev/tachyon/sites/84/2021/06/mononoke045.jpg`

This obviously breaks the image render and the return response is `Object name contains unsupported characters.`

**Comment by roborourke** [comment]
Ah ok, so that was resolved for the attachment JS but not something in the front end display then 🤔 see the prepare attachment JS filter in the AMF namespace file

**Comment by jazzsequence** [comment]
I was looking at that and working with that filter specifically doesn't do anything for the front end rendering. I was messing with the `wp_get_attachment_url` filter a bit to see if I could filter the URL on the output, but that might still be too early? The URL isn't broken yet in that filter.

**Comment by jazzsequence** [comment]
It looks like `post_thumbnail_html` might work?

**Comment by roborourke** [comment]
I've updated the PR to handle the other cases I could find in core where image URLs are constructed from what is expected to just be the file name. It may have just been the `srcset` but I threw in a `wp_get_attachment_url` filter too on a late priority. Let me know if that solves it, otherwise if you can give me some steps your following I can compare to my own testing.

**Comment by jazzsequence** [comment]
I'm seeing two different, possibly unrelated errors currently. I started noticing one yesterday but I was conflating it with the issue I was trying to look into already and that you were working on. I've been able to track both down and duplicate them consistently today. 

Let me know if this is related to combining branches that shouldn't be combined or if things should be merged to `master`/`main` by now.

AMF branch: `fallback-for-missing-sizes`
AMF WordPress branch: `main`
Altis Media branch: `update-amf-multi-provider`

-----------

### Issue 1: Cannot select a featured image from the global content repository

1. Create/edit post that does not have a featured image (or remove the featured image)
2. Click to add a featured image
3. Click to filter to only select from the Global Content Repository
4. Select an image as the featured image
5. A `GET` error will trigger at a URL like `https://altis-dev.altis.dev/wp-json/wp/v2/media/amf-14?context=edit&_locale=user`

`14` is the post ID of the correct attachment on the Global site. But simply selecting the image from the Global repository for use as a featured image does _not_ trigger the attachment post to be created locally, therefore the post doesn't exist and the API requests to that media file on the local site fail.

### Issue 2: Thumbnail image for (previously-copied-to-local) Global image (still) does not display

The front-end rendering of the image works (hooray! 🎉) but in the admin, there's still a blank space where the image should be.

1. Create/edit post that does not have a featured image (or remove the featured image)
2. Insert an image from the Global Content Repository into the _body_ of the post
3. Click to add a featured image
4. Select the _same_ image from the _local_ media library
5. The image is saved to the post and will appear in the published post/post preview but does not appear in the admin.

The console reports another `GET` error for these images as well, which appears to be the duplicated URL path thing again: `https://altis-dev.altis.dev/tachyon/sites/84/2021/06/https://altis-dev.altis.dev/tachyon/sites/84/2021/06/mononoke025.jpg`

**Review by jazzsequence — APPROVED** [review]
With the latest fixes and update to Smart Media (0.3.10) the previously reported issues have been resolved and this looks good to go.

There appears to be a new bug that is Smart Media related (dropping errors into the console) that I will create in a new issue.

**Pull request merged**
