### PR TITLE
Gallery Fixes

### PR DESCRIPTION
**Pull request by tomjn**
Fixes some PHP notices/warnings and hides the provider filter on the edit gallery screen.

### CODE REVIEW

**Comment by tomjn** [comment]
Related to #62

**Comment by tomjn** [comment]
Noting that galleries are working locally for me on a client site after making these changes. I expected more changes to be necessary for this though so I'm wary. This needs independent testing/confirmation

**Comment by tomjn** [comment]
I'd note these are still valuable fixes even if galleries aren't fixed, but this still needs fresh eyes

**Comment by roborourke** [comment]
Can you still choose external media for galleries?

**Comment by tomjn** [comment]
> Can you still choose external media for galleries?

you mean is it limited to local assets? No in the specific use case we used the clients DAM to pick images for the gallery and it worked fine

**Comment by roborourke** [comment]
I meant when choosing images for the gallery can you still select external / local / media from multiple providers? But sounds like yes

**Review by roborourke — APPROVED** [review]
Seems good to me if it solves the problem without removing functionality. Nice work @tomjn !

**Pull request merged**
